[pytest]
python_files = test_*.py
filterwarnings =
    ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated:DeprecationWarning:dateutil.tz.tz
    ignore:The `update_forward_refs` method is deprecated:DeprecationWarning:gotrue.types
    ignore:.*ARC4 has been moved.*::
    ignore:ast.NameConstant is deprecated:DeprecationWarning:reportlab.lib.rl_safe_eval
